- enoyl-ACP reductase
- decaprenylphosphoryl-beta-D-ribose oxidase
- decaprenylphosphoryl-beta-D-ribose 2-epimerase
- ATP synthase subunit c
- polyketide synthase
- trehalose monomycolate transporter
- mycobacterial membrane protein large
- fatty acid synthase
- beta-ketoacyl-ACP synthase
- acyl carrier protein
- isocitrate lyase
- DNA gyrase subunit A
- DNA gyrase subunit B
- RNA polymerase beta subunit
- RNA polymerase beta-prime subunit
- catalase-peroxidase
- arabinosyltransferase
- antigen 85A
- antigen 85B
- antigen 85C
- UDP-N-acetylglucosamine transferase
- pantothenate synthetase
- dihydrofolate reductase
- thymidylate synthase
- biotin synthase
- mycothiol ligase
- L,D-transpeptidase
- NADH dehydrogenase
- menaquinone biosynthesis protein
- cytochrome bc1 complex
- cytochrome c oxidase
- serine/threonine protein kinase
- transcriptional regulator
- two-component response regulator
